FROM php:8.1

COPY php.ini /usr/local/etc/php/

RUN apt-get update \
    && apt-get install -y zlib1g-dev mariadb-client git zip unzip vim libzip-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# composer をインストールしたい
#RUN curl -sS https://getcomposer.org/installer | php \
#    && mv composer.phar /usr/local/bin/composer \
#    && chmod +x /usr/local/bin/composer

#WORKDIR /var/www/html

#ENV COMPOSER_ALLOW_SUPERUSER 1
#ENV COMPOSER_HOME /composer
#ENV PATH $PATH:/composer/vendor/bin


