FROM php:8.1

COPY php.ini /usr/local/etc/php/

RUN apt-get update \
    && apt-get install -y zlib1g-dev mariadb-client git zip unzip vim libzip-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
